spring:
  datasource:
    url: jdbc:h2:mem:transaction?mode=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
        use_sql_comments: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        transaction: DEBUG
        orm:
          jpa: DEBUG


